import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext(null);
const STORAGE_KEY = 'dairyguard-language';

export const LANGUAGES = {
  en: 'English',
  hi: 'हिन्दी',
  kn: 'ಕನ್ನಡ',
};

const TRANSLATIONS = {
  en: {
    language: 'Language',
    dark: 'Dark',
    light: 'Light',
    addAnimal: 'Add animal',
    newHerdRecord: 'New herd record',
    animalType: 'Animal type',
    name: 'Name',
    animalId: 'Animal ID',
    breed: 'Breed',
    age: 'Age (years)',
    ownerId: 'Owner ID',
    cancel: 'Cancel',
    addToHerd: 'Add to herd',
    duplicateId: 'That animal ID is already in use. Choose another one.',
    highRiskBoard: 'High Risk Board',
    animalsFlagged: 'animals flagged',
    animal: 'Animal',
    species: 'Species',
    risk: 'Risk',
    score: 'Score',
    rumination: 'Rumination Δ',
    view: 'View',
    login: 'Log in',
    signup: 'Sign up',
    phone: 'Phone number',
    uniqueId: 'Unique ID',
    identifier: 'Sign in with',
    identifierPlaceholder: 'Enter your phone number',
    uniqueIdPlaceholder: 'Enter your unique ID',
    password: 'Password',
    fullName: 'Full name',
    signIn: 'Sign in to DairyGuard',
    createAccount: 'Create DairyGuard account',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    logIn: 'Log in',
    signUp: 'Sign up',
    enterPlatform: 'Enter Platform',
    mainPage: 'Main Page',
    herdOverview: 'Herd Overview',
    analytics: 'Analytics',
    predictions: 'Predictions',
    history: 'History',
    animals: 'Animals',
    signupWith: 'Sign up with',
    backHome: 'Back to home',
    earlyCare: 'DairyGuard AI · Early care intelligence',
    authIntro: 'Sign in or create your workspace to keep every herd signal in view.',
    allSet: 'You are all set.',
    workspaceReceived: 'Workspace request received.',
    prototypeReady: 'This prototype is ready for the next step. Continue into the platform to explore the herd view.',
    welcomeBack: 'Welcome back',
    createWorkspace: 'Create your workspace',
    yourName: 'Your name',
    passwordPlaceholder: 'At least 8 characters',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    terms: 'By continuing, you agree to the DairyGuard workspace terms and privacy policy.',
    welcomeBackBang: 'Welcome back!',
    helloPartner: 'Hello, partner!',
    loginDescription: 'To keep your herd connected, sign in with your personal details.',
    signupDescription: 'Enter your details and start your connected herd journey with us.',
    herdTrends: 'Herd-wide trends across all connected devices.',
    riskDistribution: 'Risk distribution',
    averageRisk: 'Average risk by species',
    thi: 'Shed Temperature-Humidity Index (THI)',
    historyDescription: 'A chronological log of herd events and alerts.',
    predictionTitle: 'Predictions & Recommendations',
    predictionDescription: 'Explainable, animal-specific actions generated from the fused risk vector.',
    viewRecord: 'View full animal record →',
    noRecommendations: 'No active recommendations — herd is clear.',
    speciesLabel: 'Species',
    ageLabel: 'Age',
    lactation: 'Lactation',
    riskScore: 'Risk score',
    noAnimals: 'No animals recorded for this species yet.',
    cooperative: 'Kolar Village / milk cooperative',
    healthConsole: 'Herd Health Console',
    gatewayOnline: 'Gateway online · 99.4% uptime',
    fieldSignal: 'Field signal / 24-7',
    knowSooner: 'Know sooner.',
    careBetter: 'Care better.',
    heroDescription: 'DairyGuard turns the quietest changes in behaviour and milk chemistry into a clear care window for every animal.',
    exploreSystem: 'Explore the system',
    watchDemo: 'Watch demo on YouTube',
    signalWatch: 'Signal watch',
    live: 'LIVE',
    behaviourConfidence: 'Behaviour confidence · herd average',
    earlyCareWindow: 'Early care window',
    beforeSymptoms: 'before symptoms surface',
    connectedView: 'One connected view',
    wholeHerd: 'for the whole herd',
    todayInHerd: 'Today in the herd',
    earlierSignal: 'A clearer day starts with an earlier signal.',
    liveReadings: 'Live readings from every connected animal, distilled into the care decisions that matter now.',
    herdSize: 'Herd size',
    acrossSpecies: 'across 3 species',
    needsVet: 'needs vet attention',
    averageRiskScore: 'Average risk score',
    herdWide: 'herd-wide',
    gatewayUptime: 'Gateway uptime',
    last30Days: 'last 30 days',
    liveHerdReview: 'Live Herd Review',
    updatedMoments: 'Updated moments ago',
    noRiskAnimals: 'No moderate or high risk animals right now.',
  },
  hi: {
    language: 'भाषा',
    dark: 'डार्क',
    light: 'लाइट',
    addAnimal: 'पशु जोड़ें',
    newHerdRecord: 'नया झुंड रिकॉर्ड',
    animalType: 'पशु का प्रकार',
    name: 'नाम',
    animalId: 'पशु आईडी',
    breed: 'नस्ल',
    age: 'आयु (वर्ष)',
    ownerId: 'मालिक आईडी',
    cancel: 'रद्द करें',
    addToHerd: 'झुंड में जोड़ें',
    duplicateId: 'यह पशु आईडी पहले से उपयोग में है। दूसरी आईडी चुनें।',
    highRiskBoard: 'उच्च जोखिम बोर्ड',
    animalsFlagged: 'पशु चिह्नित',
    animal: 'पशु',
    species: 'प्रजाति',
    risk: 'जोखिम',
    score: 'स्कोर',
    rumination: 'जुगाली Δ',
    view: 'देखें',
    login: 'लॉग इन',
    signup: 'साइन अप',
    phone: 'फ़ोन नंबर',
    uniqueId: 'यूनिक आईडी',
    identifier: 'इसके साथ साइन इन करें',
    identifierPlaceholder: 'अपना फ़ोन नंबर दर्ज करें',
    uniqueIdPlaceholder: 'अपनी यूनिक आईडी दर्ज करें',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    signIn: 'DairyGuard में साइन इन करें',
    createAccount: 'DairyGuard अकाउंट बनाएं',
    switchToLight: 'लाइट मोड पर जाएं',
    switchToDark: 'डार्क मोड पर जाएं',
    logIn: 'लॉग इन',
    signUp: 'साइन अप',
    enterPlatform: 'प्लेटफ़ॉर्म खोलें',
    mainPage: 'मुख्य पृष्ठ',
    herdOverview: 'झुंड का अवलोकन',
    analytics: 'विश्लेषण',
    predictions: 'पूर्वानुमान',
    history: 'इतिहास',
    animals: 'पशु',
    signupWith: 'इसके साथ साइन अप करें',
    backHome: 'होम पर वापस जाएं',
    earlyCare: 'DairyGuard AI · शुरुआती देखभाल बुद्धिमत्ता',
    authIntro: 'हर झुंड संकेत पर नज़र रखने के लिए साइन इन करें या अपना कार्यक्षेत्र बनाएं।',
    allSet: 'आप तैयार हैं।',
    workspaceReceived: 'कार्यस्थल अनुरोध प्राप्त हुआ।',
    prototypeReady: 'यह प्रोटोटाइप अगले चरण के लिए तैयार है। झुंड दृश्य देखने के लिए प्लेटफ़ॉर्म पर जाएं।',
    welcomeBack: 'वापसी पर स्वागत है',
    createWorkspace: 'अपना कार्यक्षेत्र बनाएं',
    yourName: 'आपका नाम',
    passwordPlaceholder: 'कम से कम 8 अक्षर',
    hidePassword: 'पासवर्ड छिपाएं',
    showPassword: 'पासवर्ड दिखाएं',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    terms: 'जारी रखकर, आप DairyGuard कार्यक्षेत्र की शर्तों और गोपनीयता नीति से सहमत हैं।',
    welcomeBackBang: 'वापसी पर स्वागत है!',
    helloPartner: 'नमस्ते साथी!',
    loginDescription: 'अपने झुंड को जुड़ा रखने के लिए अपनी जानकारी से साइन इन करें।',
    signupDescription: 'अपनी जानकारी दर्ज करें और अपने जुड़े झुंड की यात्रा शुरू करें।',
    herdTrends: 'सभी जुड़े उपकरणों के झुंड-व्यापी रुझान।',
    riskDistribution: 'जोखिम वितरण',
    averageRisk: 'प्रजाति के अनुसार औसत जोखिम',
    thi: 'शेड तापमान-आर्द्रता सूचकांक (THI)',
    historyDescription: 'झुंड की घटनाओं और अलर्ट का कालानुक्रमिक लॉग।',
    predictionTitle: 'पूर्वानुमान और सुझाव',
    predictionDescription: 'संयुक्त जोखिम संकेत से बनाए गए समझाने योग्य, पशु-विशिष्ट सुझाव।',
    viewRecord: 'पूरा पशु रिकॉर्ड देखें →',
    noRecommendations: 'कोई सक्रिय सुझाव नहीं — झुंड सुरक्षित है।',
    speciesLabel: 'प्रजाति',
    ageLabel: 'आयु',
    lactation: 'दुग्धावस्था',
    riskScore: 'जोखिम स्कोर',
    noAnimals: 'इस प्रजाति के लिए अभी कोई पशु दर्ज नहीं है।',
    cooperative: 'कोलार गांव / दुग्ध सहकारी',
    healthConsole: 'झुंड स्वास्थ्य कंसोल',
    gatewayOnline: 'गेटवे ऑनलाइन · 99.4% अपटाइम',
    fieldSignal: 'फील्ड संकेत / 24-7',
    knowSooner: 'जल्दी जानें।',
    careBetter: 'बेहतर देखभाल करें।',
    heroDescription: 'DairyGuard व्यवहार और दूध की रसायन में होने वाले सूक्ष्म बदलावों को हर पशु के लिए स्पष्ट देखभाल अवसर में बदलता है।',
    exploreSystem: 'सिस्टम देखें',
    watchDemo: 'YouTube पर डेमो देखें',
    signalWatch: 'संकेत निगरानी',
    live: 'लाइव',
    behaviourConfidence: 'व्यवहार विश्वास · झुंड औसत',
    earlyCareWindow: 'शुरुआती देखभाल अवसर',
    beforeSymptoms: 'लक्षण दिखने से पहले',
    connectedView: 'एक जुड़ा दृश्य',
    wholeHerd: 'पूरे झुंड के लिए',
    todayInHerd: 'आज झुंड में',
    earlierSignal: 'एक स्पष्ट दिन पहले संकेत से शुरू होता है।',
    liveReadings: 'हर जुड़े पशु की लाइव रीडिंग को अभी महत्वपूर्ण देखभाल निर्णयों में बदला गया है।',
    herdSize: 'झुंड का आकार',
    acrossSpecies: '3 प्रजातियों में',
    needsVet: 'पशु चिकित्सक की जरूरत',
    averageRiskScore: 'औसत जोखिम स्कोर',
    herdWide: 'पूरे झुंड का',
    gatewayUptime: 'गेटवे अपटाइम',
    last30Days: 'पिछले 30 दिन',
    liveHerdReview: 'लाइव झुंड समीक्षा',
    updatedMoments: 'अभी अपडेट किया गया',
    noRiskAnimals: 'अभी कोई मध्यम या उच्च जोखिम वाला पशु नहीं है।',
  },
  kn: {
    language: 'ಭಾಷೆ',
    dark: 'ಡಾರ್ಕ್',
    light: 'ಲೈಟ್',
    addAnimal: 'ಪ್ರಾಣಿಯನ್ನು ಸೇರಿಸಿ',
    newHerdRecord: 'ಹೊಸ ಹಿಂಡು ದಾಖಲೆ',
    animalType: 'ಪ್ರಾಣಿಯ ಪ್ರಕಾರ',
    name: 'ಹೆಸರು',
    animalId: 'ಪ್ರಾಣಿ ಐಡಿ',
    breed: 'ತಳಿ',
    age: 'ವಯಸ್ಸು (ವರ್ಷಗಳು)',
    ownerId: 'ಮಾಲೀಕರ ಐಡಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    addToHerd: 'ಹಿಂಡಿಗೆ ಸೇರಿಸಿ',
    duplicateId: 'ಈ ಪ್ರಾಣಿ ಐಡಿ ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ. ಬೇರೆ ಐಡಿ ಆಯ್ಕೆಮಾಡಿ.',
    highRiskBoard: 'ಹೆಚ್ಚಿನ ಅಪಾಯ ಫಲಕ',
    animalsFlagged: 'ಪ್ರಾಣಿಗಳಿಗೆ ಗುರುತು',
    animal: 'ಪ್ರಾಣಿ',
    species: 'ಪ್ರಭೇದ',
    risk: 'ಅಪಾಯ',
    score: 'ಸ್ಕೋರ್',
    rumination: 'ಮೆಲುಕು Δ',
    view: 'ವೀಕ್ಷಿಸಿ',
    login: 'ಲಾಗ್ ಇನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    uniqueId: 'ಯೂನಿಕ್ ಐಡಿ',
    identifier: 'ಇದರೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    identifierPlaceholder: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    uniqueIdPlaceholder: 'ನಿಮ್ಮ ಯೂನಿಕ್ ಐಡಿ ನಮೂದಿಸಿ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    signIn: 'DairyGuard ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    createAccount: 'DairyGuard ಖಾತೆ ರಚಿಸಿ',
    switchToLight: 'ಲೈಟ್ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
    switchToDark: 'ಡಾರ್ಕ್ ಮೋಡ್‌ಗೆ ಬದಲಾಯಿಸಿ',
    logIn: 'ಲಾಗ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    enterPlatform: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ತೆರೆಯಿರಿ',
    mainPage: 'ಮುಖ್ಯ ಪುಟ',
    herdOverview: 'ಹಿಂಡು ಅವಲೋಕನ',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    predictions: 'ಮುನ್ಸೂಚನೆಗಳು',
    history: 'ಇತಿಹಾಸ',
    animals: 'ಪ್ರಾಣಿಗಳು',
    signupWith: 'ಇದರೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    backHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    earlyCare: 'DairyGuard AI · ಆರಂಭಿಕ ಆರೈಕೆ ಬುದ್ಧಿಮತ್ತೆ',
    authIntro: 'ಪ್ರತಿ ಹಿಂಡಿನ ಸಂಕೇತವನ್ನು ಗಮನದಲ್ಲಿಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳವನ್ನು ರಚಿಸಿ.',
    allSet: 'ನೀವು ಸಿದ್ಧರಾಗಿದ್ದೀರಿ.',
    workspaceReceived: 'ಕಾರ್ಯಸ್ಥಳ ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ.',
    prototypeReady: 'ಈ ಮಾದರಿ ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸಿದ್ಧವಾಗಿದೆ. ಹಿಂಡಿನ ದೃಶ್ಯವನ್ನು ನೋಡಲು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ.',
    welcomeBack: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    createWorkspace: 'ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳವನ್ನು ರಚಿಸಿ',
    yourName: 'ನಿಮ್ಮ ಹೆಸರು',
    passwordPlaceholder: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು',
    hidePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆಮಾಡಿ',
    showPassword: 'ಪಾಸ್‌ವರ್ಡ್ ತೋರಿಸಿ',
    rememberMe: 'ನನ್ನನ್ನು ನೆನಪಿನಲ್ಲಿಡಿ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    terms: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ, ನೀವು DairyGuard ಕಾರ್ಯಸ್ಥಳದ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೀರಿ.',
    welcomeBackBang: 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    helloPartner: 'ನಮಸ್ಕಾರ ಸಂಗಾತಿ!',
    loginDescription: 'ನಿಮ್ಮ ಹಿಂಡನ್ನು ಸಂಪರ್ಕದಲ್ಲಿಡಲು ವೈಯಕ್ತಿಕ ವಿವರಗಳಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    signupDescription: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಸಂಪರ್ಕಿತ ಹಿಂಡಿನ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ.',
    herdTrends: 'ಎಲ್ಲಾ ಸಂಪರ್ಕಿತ ಸಾಧನಗಳ ಹಿಂಡು-ವ್ಯಾಪಿ ಪ್ರವೃತ್ತಿಗಳು.',
    riskDistribution: 'ಅಪಾಯ ವಿತರಣೆ',
    averageRisk: 'ಪ್ರಭೇದದ ಪ್ರಕಾರ ಸರಾಸರಿ ಅಪಾಯ',
    thi: 'ಶೆಡ್ ತಾಪಮಾನ-ಆರ್ದ್ರತೆ ಸೂಚ್ಯಂಕ (THI)',
    historyDescription: 'ಹಿಂಡಿನ ಘಟನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳ ಕಾಲಾನುಕ್ರಮದ ದಾಖಲೆ.',
    predictionTitle: 'ಮುನ್ಸೂಚನೆಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳು',
    predictionDescription: 'ಸಂಯೋಜಿತ ಅಪಾಯ ಸಂಕೇತದಿಂದ ರಚಿಸಲಾದ ವಿವರಿಸಬಹುದಾದ, ಪ್ರಾಣಿ-ನಿರ್ದಿಷ್ಟ ಕ್ರಮಗಳು.',
    viewRecord: 'ಪೂರ್ಣ ಪ್ರಾಣಿ ದಾಖಲೆಯನ್ನು ವೀಕ್ಷಿಸಿ →',
    noRecommendations: 'ಸಕ್ರಿಯ ಶಿಫಾರಸುಗಳಿಲ್ಲ — ಹಿಂಡು ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    speciesLabel: 'ಪ್ರಭೇದ',
    ageLabel: 'ವಯಸ್ಸು',
    lactation: 'ಹಾಲು ನೀಡುವ ಅವಧಿ',
    riskScore: 'ಅಪಾಯ ಸ್ಕೋರ್',
    noAnimals: 'ಈ ಪ್ರಭೇದಕ್ಕೆ ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಾಣಿಗಳು ದಾಖಲಾಗಿಲ್ಲ.',
    cooperative: 'ಕೋಲಾರ ಗ್ರಾಮ / ಹಾಲು ಸಹಕಾರಿ',
    healthConsole: 'ಹಿಂಡು ಆರೋಗ್ಯ ಕನ್ಸೋಲ್',
    gatewayOnline: 'ಗೇಟ್‌ವೇ ಆನ್‌ಲೈನ್ · 99.4% ಅಪ್‌ಟೈಮ್',
    fieldSignal: 'ಕ್ಷೇತ್ರ ಸಂಕೇತ / 24-7',
    knowSooner: 'ಮೊದಲೇ ತಿಳಿಯಿರಿ.',
    careBetter: 'ಉತ್ತಮ ಆರೈಕೆ ಮಾಡಿ.',
    heroDescription: 'DairyGuard ನಡವಳಿಕೆ ಮತ್ತು ಹಾಲಿನ ರಸಾಯನಶಾಸ್ತ್ರದಲ್ಲಿನ ಸೂಕ್ಷ್ಮ ಬದಲಾವಣೆಗಳನ್ನು ಪ್ರತಿಯೊಂದು ಪ್ರಾಣಿಗೂ ಸ್ಪಷ್ಟ ಆರೈಕೆ ಸಮಯವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ.',
    exploreSystem: 'ವ್ಯವಸ್ಥೆಯನ್ನು ಅನ್ವೇಷಿಸಿ',
    watchDemo: 'YouTube ನಲ್ಲಿ ಡೆಮೋ ನೋಡಿ',
    signalWatch: 'ಸಂಕೇತ ವೀಕ್ಷಣೆ',
    live: 'ಲೈವ್',
    behaviourConfidence: 'ನಡವಳಿಕೆ ವಿಶ್ವಾಸ · ಹಿಂಡು ಸರಾಸರಿ',
    earlyCareWindow: 'ಆರಂಭಿಕ ಆರೈಕೆ ಸಮಯ',
    beforeSymptoms: 'ಲಕ್ಷಣಗಳು ಕಾಣಿಸಿಕೊಳ್ಳುವ ಮೊದಲು',
    connectedView: 'ಒಂದು ಸಂಪರ್ಕಿತ ನೋಟ',
    wholeHerd: 'ಇಡೀ ಹಿಂಡಿಗಾಗಿ',
    todayInHerd: 'ಇಂದು ಹಿಂಡಿನಲ್ಲಿ',
    earlierSignal: 'ಸ್ಪಷ್ಟ ದಿನವು ಮುಂಚಿನ ಸಂಕೇತದಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.',
    liveReadings: 'ಪ್ರತಿ ಸಂಪರ್ಕಿತ ಪ್ರಾಣಿಯ ಲೈವ್ ಓದುವಿಕೆಗಳನ್ನು ಈಗ ಮುಖ್ಯವಾದ ಆರೈಕೆ ನಿರ್ಧಾರಗಳಾಗಿ ಸಂಕ್ಷೇಪಿಸಲಾಗಿದೆ.',
    herdSize: 'ಹಿಂಡಿನ ಗಾತ್ರ',
    acrossSpecies: '3 ಪ್ರಭೇದಗಳಲ್ಲಿ',
    needsVet: 'ಪಶುವೈದ್ಯರ ಗಮನ ಅಗತ್ಯ',
    averageRiskScore: 'ಸರಾಸರಿ ಅಪಾಯ ಸ್ಕೋರ್',
    herdWide: 'ಇಡೀ ಹಿಂಡಿನ',
    gatewayUptime: 'ಗೇಟ್‌ವೇ ಅಪ್‌ಟೈಮ್',
    last30Days: 'ಕಳೆದ 30 ದಿನಗಳು',
    liveHerdReview: 'ಲೈವ್ ಹಿಂಡು ಪರಿಶೀಲನೆ',
    updatedMoments: 'ಇದೀಗ ನವೀಕರಿಸಲಾಗಿದೆ',
    noRiskAnimals: 'ಈಗ ಯಾವುದೇ ಮಧ್ಯಮ ಅಥವಾ ಹೆಚ್ಚಿನ ಅಪಾಯದ ಪ್ರಾಣಿಗಳಿಲ್ಲ.',
  },
};

function getInitialLanguage() {
  const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
  return savedLanguage && LANGUAGES[savedLanguage] ? savedLanguage : 'en';
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  function t(key) {
    return TRANSLATIONS[language][key] ?? TRANSLATIONS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
